tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "cask"
brew "curl"
brew "git"
brew "git-flow-avh"
brew "go"
brew "mas"
brew "nvm"
brew "python@3.9"
brew "tmux"
brew "watchman"
brew "wget"
brew "yarn"
brew "htop"
brew "k6"
brew "minikube"
brew "helm"
brew "git-lfs"
brew "tree"
cask "adoptopenjdk"
cask "alt-tab"
cask "android-studio"
cask "appcleaner"
cask "avocode"
cask "cheatsheet"
cask "clean-me"
cask "docker"
cask "font-fira-code"
cask "google-chrome"
cask "graphiql"
cask "altair-graphql-client"
cask "hiddenbar"
cask "iterm2"
cask "maccy"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "openinterminal"
cask "postman"
cask "qlstephen"
cask "qlcolorcode"
cask "quicklook-csv"
cask "quicklook-json"
cask "rectangle"
cask "sourcetree"
cask "spotify"
cask "stats"
cask "visual-studio-code"
cask "alfred"
cask "wireshark"
cask "zoom"
cask "figma"
cask "lens"
cask "obs"
cask "discord"
cask "slack"
mas "LINE", id: 539883307
mas "Messenger", id: 1480068668
mas "Microsoft To Do", id: 1274495053
mas "Twitter", id: 1482454543
mas "Xcode", id: 497799835

