brew "cask"
brew "mas"
brew "git"
brew "nvm"
brew "python"
brew "yarn"
brew "wget"
brew "watchman"
brew "postgresql"
brew "go"
brew "k6"
brew "curl"
cask "google-chrome"
cask "microsoft-edge"
cask "iterm2"
cask "visual-studio-code"
cask "docker"
cask "android-studio"
cask "adoptopenjdk"
cask "pgadmin4"
cask "postman"
cask "graphiql"
cask "libreoffice"
cask "spotify"
cask "rectangle"
cask "background-music"
cask "gitkraken"
mas "Xcode",id: 497799835
mas "LINE",id: 539883307
mas "Messenger",id: 1480068668
mas "Microsoft To Do",id: 1274495053

