tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "cask"
brew "curl"
brew "git"
brew "git-flow-avh"
brew "go"
brew "mas"
brew "nvm"
brew "python@3.9"
brew "tmux"
brew "watchman"
brew "wget"
brew "yarn"
cask "adoptopenjdk"
cask "android-studio"
cask "avocode"
cask "docker"
cask "font-fira-code"
cask "google-chrome"
cask "graphiql"
cask "iterm2"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "postman"
cask "rectangle"
cask "sourcetree"
cask "spotify"
cask "visual-studio-code"
cask "zoom"
mas "LINE", id: 539883307
mas "Messenger", id: 1480068668
mas "Microsoft To Do", id: 1274495053
mas "Xcode", id: 497799835
